name: Actions on Staging Branch
on: 
  pull_request: 
    branches:
      - staging

jobs: 
  Test, Build and Deploy:
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a '${{ github.event_name }}' event."
      - run: echo "ğŸ‰ The job was triggered by '${{ github.base_ref }}' branch."    
      - run: echo "ğŸ‰ A repository secret is '${{ secrets.DEMO_KEY }}'."    
      - run: echo "ğŸ‰ A environment secret is '${{ secrets.TEST_DEMO_KEY }}'."    
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is '${{ job.status }}.'"

